### ISSUE TITLE
Retained message works only if client connects via mqtt (port 1883)

### ISSUE THREAD

**Issue by vi3tnd** [rmqtt/rmqtt#118]
I have made some tests for retained message feature, where clients connect to different ports (tested with mqtt - 1883, mqtts - 8883, ws - 8080, wss - 8443). The weird thing is that it works with the mqtt (port 1883) only, the others do not work at all.

- For clients: I have tried MQTT Explorer and MQTTX.

- For rmqtt: I have used both of single node mode (configured ram as storage), as well as cluster mode (configured redis as storage).

I got the same result. Does anybody know why?

**Comment by bittcrafter** [comment]
Hello, first of all, thank you for your interest in RMQTT. The issues you are encountering may be due to the following reasons:

1. First, ensure that the "rmqtt-retainer" plugin is enabled by default.
2. In different listening modes, you also need to enable the corresponding configuration switches below, as they are turned off by default:
   - `listener.tcp.external.retain_available = true`  // 1883
   - `listener.tcp.internal.retain_available = true`   // 11883
   - `listener.tls.external.retain_available = true`    // 8883
   - `listener.ws.external.retain_available = true`     // 8080
   - `listener.wss.external.retain_available = true`    // 8443


Let me know if you need any more help!

**Comment by vi3tnd** [comment]
It works, thank you. I just don't know these configurations exist for other listeners.

**Comment by akrizs** [comment]
@bittcrafter how many other configuration keys are there that are not documented in the default `rmqtt.toml` file?
i see when testing the retainer with redis that there is an expire on the message, how can that be set to not expire since the retained messages should be available to devices no matter when they connect ?
