### ISSUE TITLE
Upgrade salvo web server to latest 0.44 and add logging and add webserver configuration

### ISSUE THREAD

**Issue by greenpdx** [rmqtt/rmqtt#26]
rmqtt uses 0.37.9 salvo and the interface has changed in 0.44.  
step one, would be to upgrade rmqtt to use salvo 0.44 api.
step two, is to add logging to http requests.
step three, add configuration for salvo web server in rmqtt config.

I am trying to add static webpages to http-api/api.rs:router function using StaticDir but I am getting 404, not sure where it is looking for the files.

**Comment by rmqtt** [comment]
1. The reason why salvo 0.40 and later versions were not used is because salvo 0.37 uses the latest official version of super ("0.14"), while salvo 0.4x uses super ("1.0.0 rc.3")

3. The function of adding HTTP request logs has been added to the development plan.

4. What salvo web server configurations need to be added? Can you provide examples?

5. Using StaticDir but I am getting 404. It is recommended to post your question in the salvo community.

Finally, thank you for your attention and use of rmqtt.

**Comment by greenpdx** [comment]
I would like rmqtt have a web interface with http-api so it would be able to function as a web-server also. MQTT is great for communication but for a user interface a web server is the best.

**Comment by rmqtt** [comment]
My understanding is that webserver is not a necessary feature of mqtt broker. Based on your requirements, it is recommended to deploy additional webserver services, such as nginx or haproxy.

**Comment by greenpdx** [comment]
It is not necessary but it is a nice feature; 
Use Case
A SBC controls a network of IoT using mqtt protocol. It has a web application written to control the system. Space is limited. rmqtt server host the static app, another web server is not needed for one application. 
Create a plugin; http-web-server

**Comment by rmqtt** [comment]
Based on your business situation, you can implement the ‘http-web-server’ plugin to solve your problem. But this is not a part of rmqtt, so you can implement this ‘http-web-server’ plugin and recompile rmqtt. The plugin implementation can refer to: https://github.com/rmqtt/rmqtt/tree/master/rmqtt-plugins/rmqtt-plugin-template
