### ISSUE TITLE
remove unnecessary variable to be mutable

### ISSUE THREAD

**Issue by bodypumper** [rmqtt/rmqtt#31]
code:after pull origin master
ide:vscode
message:warning: variable does not need to be mutable
image:
<img width="515" alt="image" src="https://github.com/rmqtt/rmqtt/assets/44149782/7e3b7f0c-b5ef-4003-b182-3b62d017037c">

**Comment by rmqtt** [comment]
Thank you for your attention to RMQTT, this problem will be fixed in the next version.

thank you!



---- Replied Message ----
| From | ***@***.***> |
| Date | 08/14/2023 09:49 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [rmqtt/rmqtt] remove unnecessary variable to be mutable (Issue #31) |

code:after pull origin master
ide:vscode
message⚠️ variable does not need to be mutable
image:
