### ISSUE TITLE
Subscriptions after server restart and data persistence.

### ISSUE THREAD

**Issue by AmirDotDev0** [rmqtt/rmqtt#45]
First off, I would like to take a moment to express my sincere gratitude for the incredible work you've done on the Rmqtt MQTT broker.

I recently started using Rmqtt and I have been thoroughly impressed with its features and performance. It has significantly enhanced my projects, and for that, I am truly thankful.

However, I wanted to share a concern I've encountered. It appears that subscriptions are not persisting after server restarts. This has caused inconvenience as clients need to subscribe again after every server restart. I believe a more robust subscription storage solution would greatly improve the user experience.

Additionally, I would appreciate guidance on how to properly stop the broker. Clear documentation on this aspect would be immensely helpful for users like me.

Once again, thank you for your hard work and dedication. I look forward to seeing Rmqtt continue to flourish and improve.

**Comment by rmqtt** [comment]
1. First and foremost, I'd like to express my gratitude for your support and affirmation of RMQTT. This will serve as the driving force for me to continue developing and refining it.

2. Regarding the issue of subscription persistence, it is already part of my development plan. Future versions will implement session and message persistence, which will include the persistence of subscription relationships. Therefore, when clients connect or reconnect, if "session present" returns false, they will



---- Replied Message ----
| From | ***@***.***> |
| Date | 10/01/2023 23:47 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [rmqtt/rmqtt] Subscriptions after server restart and data persistence. (Issue #45) |

First off, I would like to take a moment to express my sincere gratitude for the incredible work you've done on the Rmqtt MQTT broker.

I recently started using Rmqtt and I have been thoroughly impressed with its features and performance. It has significantly enhanced my projects, and for that, I am truly thankful.

However, I wanted to share a concern I've encountered. It appears that subscriptions are not persisting after server restarts. This has caused inconvenience as clients need to subscribe again after every server restart. I believe a more robust subscription storage solution would greatly improve the user experience.

Additionally, I would appreciate guidance on how to properly stop the broker. Clear documentation on this aspect would be immensely helpful for users like me.

Once again, thank you for your hard work and dedication. I look forward to seeing Rmqtt continue to flourish and improve.

**Comment by rmqtt** [comment]
1. First and foremost, I'd like to express my gratitude for your support and affirmation of RMQTT. This will serve as the driving force for me to continue developing and refining it.

2. Regarding the issue of subscription persistence, it is already part of my development plan. Future versions will implement session and message persistence, which will include the persistence of subscription relationships. Therefore, when clients connect or reconnect, if "session present" returns false, they will need to re-subscribe.

3. As for the question of how to stop the Broker, if the RMQTT broker was started within a container, you can simply stop the container. Otherwise, you can terminate the process directly. This is certainly not an elegant way to stop the Broker, and we will consider implementing a more graceful solution in future versions.

4. Once again, I want to express my appreciation for your support and affirmation of RMQTT. Thank you.

**Comment by rmqtt** [comment]
1. First and foremost, I'd like to express my gratitude for your support and affirmation of RMQTT. This will serve as the driving force for me to continue developing and refining it.

2. Regarding the issue of subscription persistence, it is already part of my development plan. Future versions will implement session and message persistence, which will include the persistence of subscription relationships. Therefore, when clients connect or reconnect, if "session present" returns false, they will need to re-subscribe.

3. As for the question of how to stop the Broker, if the RMQTT broker was started within a container, you can simply stop the container. Otherwise, you can terminate the process directly. This is certainly not an elegant way to stop the Broker, and we will consider implementing a more graceful solution in future versions.

4. Once again, I want to express my appreciation for your support and affirmation of RMQTT. Thank you.

**Comment by AmirOsman2020** [comment]
I'm really impressed with the current version, and I'm eagerly anticipating future updates. The addition of persistent storage for subscriptions and any other data, even after server restarts, would greatly enhance the user experience. Integrating this feature with external databases like CasandraDB, ScyllaDB, or MongoDB could further improve the overall functionality and reliability of the system. Looking forward to these exciting enhancements!

**Comment by rmqtt** [comment]
The storage of session information and published messages has been implemented. For details, see: [v0.3.0](https://github.com/rmqtt/rmqtt/releases)  [store-session.md](https://github.com/rmqtt/rmqtt/blob/master/docs/en_US/store-session.md) [store-message.md](https://github.com/rmqtt/rmqtt/blob/master/docs/en_US/store-message.md)
