### ISSUE TITLE
Can the rmqtt cluster mode be infinitely horizontally expanded? How many devices can the cluster mode support online at the same time?

### ISSUE THREAD

**Issue by worldlg** [rmqtt/rmqtt#75]

**Comment by rmqtt** [comment]
In our system, the rmqtt cluster mode cannot be infinitely horizontally expanded due to the nature of the clustering techniques it supports. 

1. **Broadcast Mode**: 
   - **Scalability**: This mode is designed to broadcast messages to all nodes in the cluster. Hence, it is not infinitely scalable.
   - **Optimal Configuration**: It is recommended to have no more than 3 nodes, with 2 nodes being the most optimal configuration. This limitation helps manage the overhead and ensures efficient message broadcasting without overwhelming the network.

2. **Raft Algorithm Mode**: 
   - **Scalability**: The Raft algorithm allows for better scalability and reliability compared to the broadcast mode.
   - **Optimal Configuration**: While this mode provides improved fault tolerance and consistency, the recommended cluster sizes are 3, 5, or 7 nodes. These configurations strike a balance between performance and reliability, with odd numbers helping to avoid split-brain scenarios.

The number of devices that the cluster mode can support online simultaneously depends on several factors, including the server hardware configuration, the chosen clustering mode, and the number of nodes in the cluster.

For detailed performance metrics and benchmarks, please refer to the rmqtt benchmark testing report: [rmqtt Benchmark Testing](https://github.com/rmqtt/rmqtt/blob/master/docs/en_US/benchmark-testing.md).
