### ISSUE TITLE
Could not compile from source code

### ISSUE THREAD

**Issue by longzou** [rmqtt/rmqtt#8]
Rust 1.69.0
Source Code 0.26.0

The errors are below:

error: failed to run custom build command for `rmqtt v0.2.10 (E:\servers\sources\rmqtt\rmqtt)`

Caused by:
  process didn't exit successfully: `E:\servers\sources\rmqtt\target\debug\build\rmqtt-691acc4cc66764fd\build-script-build` (exit code: 101)
  --- stdout
  out: E:\servers\sources\rmqtt\target\debug\build\rmqtt-c73114283d9fa88b\out
  cargo:rerun-if-changed=pb.proto
  cargo:rerun-if-changed=src/grpc/proto

  --- stderr
  thread 'main' panicked at 'Could not find `protoc` installation and this build crate cannot proceed without
      this knowledge. If `protoc` is installed and this crate had trouble finding
      it, you can set the `PROTOC` environment variable with the specific path to your
      installed `protoc` binary.You can download it from https://github.com/protocolbuffers/protobuf/releases or from your package manager.

  For more information: https://docs.rs/prost-build/#sourcing-protoc
  ', C:\Users\mekot\.cargo\registry\src\github.com-1ecc6299db9ec823\prost-build-0.11.9\src\lib.rs:1457:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `rmqtt-raft v0.2.4`

Caused by:
  process didn't exit successfully: `E:\servers\sources\rmqtt\target\debug\build\rmqtt-raft-20c6376ba58d4924\build-script-build` (exit code: 101)
  --- stdout
  out: E:\servers\sources\rmqtt\target\debug\build\rmqtt-raft-6b26a9737cfa55aa\out
  cargo:rerun-if-changed=raft_service.proto
  cargo:rerun-if-changed=proto/

  --- stderr
  thread 'main' panicked at 'Could not find `protoc` installation and this build crate cannot proceed without
      this knowledge. If `protoc` is installed and this crate had trouble finding
      it, you can set the `PROTOC` environment variable with the specific path to your
      installed `protoc` binary.You can download it from https://github.com/protocolbuffers/protobuf/releases or from your package manager.

  For more information: https://docs.rs/prost-build/#sourcing-protoc
  ', C:\Users\mekot\.cargo\registry\src\github.com-1ecc6299db9ec823\prost-build-0.11.9\src\lib.rs:1457:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error[E0793]: reference to packed field is unaligned
    --> C:\Users\mekot\.cargo\registry\src\github.com-1ecc6299db9ec823\ntapi-0.3.7\src\ntexapi.rs:2783:52
     |
2783 |         *tick_count.QuadPart_mut() = read_volatile(&(*USER_SHARED_DATA).u.TickCountQuad);
     |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
     = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
    --> C:\Users\mekot\.cargo\registry\src\github.com-1ecc6299db9ec823\ntapi-0.3.7\src\ntexapi.rs:2807:25
     |
2807 |         ((read_volatile(&(*USER_SHARED_DATA).u.TickCountQuad)
     |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
     = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

For more information about this error, try `rustc --explain E0793`.
error: could not compile `ntapi` due to 2 previous errors

**Comment by rmqtt** [comment]
hi, protoc must be installed first



---- Replied Message ----
| From | ***@***.***> |
| Date | 05/08/2023 16:09 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [rmqtt/rmqtt] Could not compile from source code (Issue #8) |

Rust 1.69.0
Source Code 0.26.0

The errors are below:

error: failed to run custom build command for rmqtt v0.2.10 (E:\servers\sources\rmqtt\rmqtt)

Caused by:
process didn't exit successfully: E:\servers\sources\rmqtt\target\debug\build\rmqtt-691acc4cc66764fd\build-script-build (exit code: 101)
--- stdout
out: E:\servers\sources\rmqtt\target\debug\build\rmqtt-c73114283d9fa88b\out
cargo:rerun-if-changed=pb.proto
cargo:rerun-if-changed=src/grpc/proto

--- stderr
thread 'main' panicked at 'Could not find protoc installation and this build crate cannot proceed without
this knowledge. If protoc is installed and this crate had trouble finding
it, you can set the PROTOC environment variable with the specific path to your
installed protoc binary.You can download it from https://github.com/protocolbuffers/protobuf/releases or from your package manager.

For more information: https://docs.rs/prost-build/#sourcing-protoc
', C:\Users\mekot.cargo\registry\src\github.com-1ecc6299db9ec823\prost-build-0.11.9\src\lib.rs:1457:10
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for rmqtt-raft v0.2.4

Caused by:
process didn't exit successfully: E:\servers\sources\rmqtt\target\debug\build\rmqtt-raft-20c6376ba58d4924\build-script-build (exit code: 101)
--- stdout
out: E:\servers\sources\rmqtt\target\debug\build\rmqtt-raft-6b26a9737cfa55aa\out
cargo:rerun-if-changed=raft_service.proto
cargo:rerun-if-changed=proto/

--- stderr
thread 'main' panicked at 'Could not find protoc installation and this build crate cannot proceed without
this knowledge. If protoc is installed and this crate had trouble finding
it, you can set the PROTOC environment variable with the specific path to your
installed protoc binary.You can download it from https://github.com/protocolbuffers/protobuf/releases or from your package manager.

For more information: https://docs.rs/prost-build/#sourcing-protoc
', C:\Users\mekot.cargo\registry\src\github.com-1ecc6299db9ec823\prost-build-0.11.9\src\lib.rs:1457:10
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
error[E0793]: reference to packed field is unaligned
--> C:\Users\mekot.cargo\registry\src\github.com-1ecc6299db9ec823\ntapi-0.3.7\src\ntexapi.rs:2783:52
|
2783 | *tick_count.QuadPart_mut() = read_volatile(&(*USER_SHARED_DATA).u.TickCountQuad);
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
= help: copy the field contents to a local variable, or replace the reference with a raw pointer and use read_unaligned/write_unaligned (loads and stores via *p must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
--> C:\Users\mekot.cargo\registry\src\github.com-1ecc6299db9ec823\ntapi-0.3.7\src\ntexapi.rs:2807:25
|
2807 | ((read_volatile(&(*USER_SHARED_DATA).u.TickCountQuad)
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
= help: copy the field contents to a local variable, or replace the reference with a raw pointer and use read_unaligned/write_unaligned (loads and stores via *p must be properly aligned even when using raw pointers)

For more information about this error, try rustc --explain E0793.
error: could not compile ntapi due to 2 previous errors

**Comment by qcjxberin** [comment]
需要怎么安装协议的？

**Comment by rhello2999** [comment]
去https://github.com/protocolbuffers/protobuf/releases下载对应平台的protoc， 比如windows平台应该下载：https://github.com/protocolbuffers/protobuf/releases/download/v23.2/protoc-23.2-win64.zip
